name: Install and Test a JDK

on:
  push:
    branches: [ main ]

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      #- name: Checkout
      #  uses: actions/checkout@v2

      - name: Setup Java
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
          version: latest
          install: true

      - name: Test our JDK
        run: |
          pwd
          ls -la
          java src/dev/java/Hello.java