name: Setup Java and Test it!

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
          version: latest
          install: true

#      - name: Setup
#        run: |
#          npm install