name: Setup Java and Test it!

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
          version: latest
          install: true

      - name: Setup
        run: |
          npm install

      - name: Build
        run: |
          gulp deploy

      - name: Deploy
        uses: carimura/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: site